version: '2'
services:
    webservice-app:
        image: webservice
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://webservice-postgresql:5432/webservice
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    webservice-postgresql:
        extends:
            file: postgresql.yml
            service: webservice-postgresql
